version: "3.8"
services:
  evaluator:
    build: ./evaluator
    container_name: evaluator
    volumes:
      - type: bind
        source: ./solutions
        target: /opt/solutions
    ports:
      - 4000
  database: 
    image: mysql:latest
    container_name: database
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: InfoTest
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./mysql/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks: 
      - internal
      - dbnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    links:
      - database
    depends_on:
      - database
    ports:
      - "8080:80"
    networks:
      - dbnet
  httpd:
    build: ./apache
    container_name: apache
    volumes:
      - type: bind
        source: ./www
        target: /var/www/html
      - type: bind
        source: ./solutions
        target: /opt/solutions
    depends_on: 
      - database
    ports:
      - "80:80"
    networks:
      - internal
      - external

networks:
  dbnet:
  internal:
  external:
